site_name: WuJing's Blog
site_url: https://realwujing.github.io
site_author: Wu Jing
site_description: 技术笔记与资源库

docs_dir: docs
site_dir: site

repo_name: realwujing/realwujing.github.io
repo_url: https://github.com/realwujing/realwujing.github.io
edit_uri: blob/main/

theme:
  name: material
  custom_dir: overrides
  language: zh
  font:
    text: Noto Sans SC
    code: JetBrains Mono
  features:
    - navigation.top
    - navigation.indexes
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: 深色模式
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: 浅色模式
  icon:
    repo: fontawesome/brands/github

plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: plantuml
          class: plantuml
          format: !!python/name:plantuml_fence.plantuml_formatter
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/tex-mml-chtml.min.js