/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp com.scorpio.test.xml -i test.h -a valueAdaptor -l test
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "valueAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class ValueAdaptor
 */

ValueAdaptor::ValueAdaptor(test *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

ValueAdaptor::~ValueAdaptor()
{
    // destructor
}

Book ValueAdaptor::book(qlonglong &out1)
{
    // handle method call com.scorpio.test.value.book
    return parent()->book(out1);
}

int ValueAdaptor::maxValue()
{
    // handle method call com.scorpio.test.value.maxValue
    return parent()->maxValue();
}

int ValueAdaptor::minValue()
{
    // handle method call com.scorpio.test.value.minValue
    return parent()->minValue();
}

int ValueAdaptor::value()
{
    // handle method call com.scorpio.test.value.value
    return parent()->value();
}

