apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "9"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"7"},"creationTimestamp":"2022-08-03T08:41:51Z","generation":7,"labels":{"app":"linglong-server"},"name":"linglong-server","namespace":"linglong","resourceVersion":"1191324","uid":"db807e56-3330-483d-bb0d-c26a354f9f36"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"linglong-server"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"annotations":{"kubectl.kubernetes.io/restartedAt":"2022-08-03T17:50:01+08:00"},"creationTimestamp":null,"labels":{"app":"linglong-server"}},"spec":{"containers":[{"image":"hub.deepin.com/wuhan_v23_linglong/linglong-server:develop-snipe","imagePullPolicy":"Always","name":"linglong-server","ports":[{"containerPort":8888,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/data/linglong","name":"linglong-server-data"},{"mountPath":"/service/config.yaml","name":"linglong-server-config-yaml","subPath":"config.yaml"}]}],"dnsPolicy":"ClusterFirst","imagePullSecrets":[{"name":"hub-deepin-token"}],"restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30,"volumes":[{"name":"linglong-server-data","persistentVolumeClaim":{"claimName":"linglong-server-pv"}},{"configMap":{"defaultMode":420,"items":[{"key":"config.yaml","path":"config.yaml"}],"name":"config.yaml"},"name":"linglong-server-config-yaml"}]}}},"status":{"availableReplicas":1,"conditions":[{"lastTransitionTime":"2022-08-03T09:24:49Z","lastUpdateTime":"2022-08-03T09:24:49Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"lastTransitionTime":"2022-08-03T10:14:44Z","lastUpdateTime":"2022-08-04T01:52:10Z","message":"ReplicaSet \"linglong-server-76b894899f\" is progressing.","reason":"ReplicaSetUpdated","status":"True","type":"Progressing"}],"observedGeneration":7,"readyReplicas":1,"replicas":2,"unavailableReplicas":1,"updatedReplicas":1}}
  creationTimestamp: "2022-08-03T08:41:51Z"
  generation: 10
  labels:
    app: linglong-server
  name: linglong-server
  namespace: linglong
  resourceVersion: "1207680"
  uid: db807e56-3330-483d-bb0d-c26a354f9f36
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: linglong-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2022-08-04T05:01:40Z"
      creationTimestamp: null
      labels:
        app: linglong-server
    spec:
      containers:
      - image: hub.deepin.com/wuhan_v23_linglong/linglong-server:develop-snipe
        imagePullPolicy: Always
        name: linglong-server
        ports:
        - containerPort: 8888
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data/linglong
          name: linglong-server-data
        - mountPath: /service/config.yaml
          name: linglong-server-config-yaml
          subPath: config.yaml
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: linglong-server-data
        persistentVolumeClaim:
          claimName: linglong-server-pv
      - configMap:
          defaultMode: 420
          items:
          - key: config.yaml
            path: config.yaml
          name: config.yaml
        name: linglong-server-config-yaml
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-08-03T09:24:49Z"
    lastUpdateTime: "2022-08-03T09:24:49Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-08-04T04:59:19Z"
    lastUpdateTime: "2022-08-04T05:01:42Z"
    message: ReplicaSet "linglong-server-5d46bc6b8c" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 10
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
