apiVersion: v1
kind: PersistentVolume
metadata:
  name: linglong-server-pv
  namespace: linglong
spec:
  storageClassName: linglong-server-pv
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /home/linglong/work/k8s-data/linglong-server-data
