apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "6"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"4"},"creationTimestamp":"2022-08-03T06:41:01Z","generation":4,"labels":{"app":"linglong-homepage"},"name":"linglong-homepage","namespace":"linglong","resourceVersion":"1207992","uid":"f774eb10-92be-41e6-ade1-e687c7a432d8"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"linglong-homepage"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"annotations":{"kubectl.kubernetes.io/restartedAt":"2022-07-19T10:07:12+08:00"},"creationTimestamp":null,"labels":{"app":"linglong-homepage"}},"spec":{"containers":[{"image":"hub.deepin.com/wuhan_v23_linglong/linglong-homepage:develop-snipe","imagePullPolicy":"Always","name":"linglong-homepage","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"availableReplicas":1,"conditions":[{"lastTransitionTime":"2022-08-03T06:57:36Z","lastUpdateTime":"2022-08-03T06:57:36Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"lastTransitionTime":"2022-08-04T05:05:07Z","lastUpdateTime":"2022-08-04T05:05:07Z","message":"ReplicaSet \"linglong-homepage-5648dfc65d\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"}],"observedGeneration":4,"readyReplicas":1,"replicas":1,"updatedReplicas":1}}
  creationTimestamp: "2022-08-03T06:41:01Z"
  generation: 6
  labels:
    app: linglong-homepage
  name: linglong-homepage
  namespace: linglong
  resourceVersion: "1212999"
  uid: f774eb10-92be-41e6-ade1-e687c7a432d8
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: linglong-homepage
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2022-08-04T05:59:49Z"
      creationTimestamp: null
      labels:
        app: linglong-homepage
    spec:
      containers:
      - image: hub.deepin.com/wuhan_v23_linglong/linglong-homepage:develop-snipe
        imagePullPolicy: Always
        name: linglong-homepage
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-08-03T06:57:36Z"
    lastUpdateTime: "2022-08-03T06:57:36Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-08-04T05:05:07Z"
    lastUpdateTime: "2022-08-04T05:59:50Z"
    message: ReplicaSet "linglong-homepage-64895d8546" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 6
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
