######################################################################
# Automatically generated by qmake (3.0) ?? 10? 21 20:08:05 2021
######################################################################

QT+=widgets
TEMPLATE = app
TARGET = hellowidget
INCLUDEPATH += .

# Input
HEADERS += hellowidget.h
SOURCES += hellowidget.cpp main.cpp
