apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
  creationTimestamp: "2022-07-18T13:43:43Z"
  generation: 4
  labels:
    app: linglong-web-store
  name: linglong-web-store
  namespace: linglong
  resourceVersion: "968340"
  uid: 0a2b85d8-6fc4-4bcb-9358-93ead21554c2
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: linglong-web-store
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2022-07-19T13:16:47+08:00"
      creationTimestamp: null
      labels:
        app: linglong-web-store
    spec:
      containers:
      - image: hub.deepin.com/wuhan_v23_linglong/linglong-web-store:develop-snipe
        imagePullPolicy: IfNotPresent
        name: linglong-web-store
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-07-18T13:43:43Z"
    lastUpdateTime: "2022-07-19T05:16:48Z"
    message: ReplicaSet "linglong-web-store-789b986b68" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2022-08-02T05:04:37Z"
    lastUpdateTime: "2022-08-02T05:04:37Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 4
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
