apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linglong-server-pv
  namespace: linglong
spec:
  storageClassName: linglong-server-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
